config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resource :admin_session

  resources :posts do
    resources :comments
  end

  resources :admin_sessions

  resources :messages

  get '/home' => 'pages#home'
  get '/about' => 'pages#about'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	acts_as_authentic
end

app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController  
  def show
  	redirect_to posts_path
  end

  def new
    @admin_session = AdminSession.new
  end
 
  def create
    @admin_session = AdminSession.new(params[:admin_session])
    if @admin_session.save
      flash[:notice] = "Login successful!"
      redirect_to posts_path
    else
      render :action => :new
    end
  end
 
  def destroy
  	current_admin_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_to "/home"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details
 
  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
 
  helper_method :current_admin_session, :current_admin
 
  private
  def current_admin_session
    return @current_admin_session if defined?(@current_admin_session)
    @current_admin_session = AdminSession.find
  end
 
  def current_admin
    return @current_admin if defined?(@current_admin)
    @current_admin = current_admin_session && current_admin_session.admin
  end
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		@comment.save
		flash[:notice] = "Comment saved!"
		redirect_to post_path(@post)
	end

	private
	def comment_params
		params.require(:comment).permit(:author, :text)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
		@messages = Message.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)
		if @message.save
			flash[:notice] = "Message Sent!"
			redirect_to "/about"
		else
			render :new
		end
	end

	def destroy
		message = Message.find(params[:id])
		message.destroy
		flash[:notice] = "#Message has been deleted"
		redirect_to messages_path
	end

	private
	def message_params
		params.require(:message).permit(:name, :email, :text)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def Home
	end

	def about
		@message = Message.new
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :login_required, :except => [:index, :show]

	def index
		@posts = Post.paginate(:page => params[:page], :per_page => 10)
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@post = Post.new
		@comment = Comment.new(post_id: params[:post_id])
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "#{@post.title} saved!"
			redirect_to @post
		else
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			flash[:notice] = "#{@post.title} updated!"
			redirect_to @post
		else
			render :edit
		end
	end

	def destroy
		post = Post.find(params[:id])
		post.destroy
		flash[:notice] = "#{post.title} has been deleted"
		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end

	def login_required
  		unless current_admin
    		flash[:error] = 'Only logged in admins can access this page.'
    		redirect_to posts_path
  		end
	end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin_sessions/_login_form.html.erb
<%= simple_form_for (@admin_session), :url => admin_session_path do |f| %>

   <% @admin_session.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>
  <div class="post">
    <p>
      <%= f.label :login %><br />
      <%= f.text_field :login %>
    </p>
   
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
   
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/admin_sessions/new.html.erb
<title>Earl Sabal's Webpage</title>

<h1>Login Page</h1>

<%= render "login_form" %>>

app/views/layouts/_cover.html.erb
<!-- Bootstrap core CSS -->
<%= stylesheet_link_tag("bootstrap.min.css") %>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

<!-- Custom styles for this template -->
<%= stylesheet_link_tag("app_layout.css") %>

app/views/layouts/_flash_msg.html.erb
<% flash.each do |name, msg| %>
	<%= content_tag :p, msg if msg.is_a?(String) %>
<% end %>

app/views/layouts/_javascript.html.erb
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="app/vendor/assets/javascripts/jquery.min.js"><\/script>')</script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

app/views/layouts/_login.html.erb
<% if current_admin %>
	<div class="post">
		<p><%= button_to 'Logout', admin_session_path(current_admin_session), :method => :delete %></p>
	</div>	
<% else %>
	<p><%= link_to 'Login', new_admin_session_path,:class => "btn btn-danger" %></p>
<% end %>

app/views/layouts/_meta_tags.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">

app/views/layouts/_navbar.html.erb
<nav>
	<ul class="nav masthead-nav">
	  <li><%= link_to "Home", "/home" %></li>
	  <li><%= link_to "Projects", posts_path %></li>
	  <li><%= link_to "About Me/Contact", "/about" %></li>
	  <% if current_admin %>
  		<li><%= link_to "Messages", messages_path %></li>
  	  <% end %>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang= "en">
<head>
  <%= render "layouts/meta_tags" %>
  <%= render "layouts/flash_msg" %>
  <%= render "layouts/cover" %>
</head>
<body>

  <div class="site-wrapper">

    <div class="site-wrapper-inner">
      <div class="cover-container">      
        <div class="masthead clearfix">
            <%= render "layouts/navbar" %>
            <div align= "left"><%= render "layouts/login" %></div>
        </div>
       
        <div class="inner cover">

  			   <%= yield %>

      	</div>
        <div class="mastfoot">
        </div>
      </div>
    </div>
  </div> 


<%= render "layouts/javascript" %>

</body>


</html>

app/views/messages/_delete_button.html.erb
<div class="post">
	<%= button_to 'Delete', message_path(@message), :method => :delete, :confirm => "Are you sure?" %><br />
</div>

app/views/messages/_messages.html.erb
<% @messages.each do |message| %>
  <div class="row">
    <h2><%= message.name %></h2>
    <p> <%= message.email %></p>
    <p> <%= message.text %></p>
    <% @message = message %>
    <%= render "delete_button" %>
  </div>
<% end %>

<%= will_paginate @messages %>

app/views/messages/index.html.erb
<title>My Messages</title>

<h1>My Messages</h1>
<div class="transbox">
  <% if current_admin %>
    <%= render "messages" %>
  <% else %>
    <p>You are not authorized to view this information!</p>
  <% end %>
</div>

app/views/pages/_form.html.erb
<div class="post">
	<%= simple_form_for (@message) do |form| %>
	  <p>
	    <%= form.label :name %><br/>
	    <%= form.text_field :name %>
	  </p>

	  <p>
	    <%= form.label :email %><br/>
	    <%= form.text_field :email %>
	  </p>
	 
	  <p>
	    <%= form.label :text %><br/>
	    <%= form.text_area :text %>
	  </p>
	 
	  <%= button_to 'Submit Message', :method => :submit %>
	<% end %>
</div>

app/views/pages/_linkedin.html.erb
<br /><%= link_to (image_tag("linkedin_logo.png", size: '40x40')), 'https://www.linkedin.com/in/earl-sabal-894993103' %><br />

app/views/pages/_profile_pic.html.erb
<br /><%= image_tag("Profile Pic.jpg", size: '240x240') %>

app/views/pages/_projects_button.html.erb
<%= link_to 'My Projects', posts_path,:class => "btn btn-lg btn-default"  %>

app/views/pages/about.html.erb
<title>About Me & Contact Information</title>

<h1>About Me & Contact Information</h1>

<div class="transbox">
	<%= render "profile_pic" %>
	<div align="left">
		<br />
		<p> • Education: Attended San Jose State University majoring in Software Engineering</p>
		<p> • Experienced programming languages: Java & Ruby</p>
		<p> • Familiar with programming languages: Javascript & HTML</p>
		<p> • Experience working with Ruby on Rails</p>
		<p> • Experience in working with both Windows and Apple computers</p>
		<p> • In depth knowledge of Microsoft Office software's: Microsoft Word, Excel, Powerpoint</p>
	</div>

	<h1>Contact Information</h1>
	<p>Email: earlsabal@gmail.com</p>
	<p>Or leave me a message with your name, email, and message</p>
	<%= render "form" %>
	<%= render "linkedin" %><br />
</div>

app/views/pages/home.html.erb
<title>Earl Sabal's Webpage</title>

<body>  
	<h1>My Webpage</h1>
	<p class="lead">
    	<%= render "projects_button"  %>
    </p>
</body>

app/views/posts/_admin_options.html.erb
<% if current_admin %>
  <div class="post">
    <%= render "edit_delete_options" %>
  </div>
<% end %>

app/views/posts/_comments.html.erb
<h3>Comments</h3>

<% @post.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.author %>
  </p>
 
  <p>
    <b>Comment:</b>
    <%= simple_format comment.text %>
  </p>
<% end %>

<%= will_paginate @comments %>

app/views/posts/_edit_delete_options.html.erb
<p>
  Admin Actions: 
  <%= link_to 'Edit', edit_post_path(@post) %> 
  <%= button_to 'Delete', post_path(@post), :method => :delete, :confirm => "Are you sure?" %>
</p>

app/views/posts/_form.html.erb
<div class="post">
	<%= simple_form_for (@post) do |form| %>
	  <p>
	    <%= form.label :title %><br/>
	    <%= form.text_field :title %>
	  </p>
	 
	  <p>
	    <%= form.label :body %><br/>
	    <%= form.text_area :body %>
	  </p>
	 
	  <%= button_to 'Submit Post', :method => :submit %>
	<% end %>
</div>

app/views/posts/_new_admin_post.html.erb
<% if current_admin %>
	<p>
	  Admin actions: <%= link_to 'New Post', new_post_path %>
	</p>
<% end %>

app/views/posts/_post_comment.html.erb
<div class="post">
<h3>Post Your Comment</h3>
  <%= simple_form_for([@post, @post.comments.build]) do |f| %>
    <div class="field">
      <%= f.label :author %><br />
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :text %><br />
      <%= f.text_area :text %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
	<div class="row">
	  <h2><%= link_to (post.title), post_path(post) %></h2>
	  <p>
	    <%= simple_format(truncate(post.body, length: 20)) %>
	  </p>
	</div>
<% end %>

<%= will_paginate @posts %>

app/views/posts/edit.html.erb
<title>Edit Post</title>
<div class="transbox">
	<% if current_admin %>
		<h1><%= "Editing #{@post.title}" %></h1>
		<%= render "form" %>
	<% else %>
			<p>You are not authorized to edit or delete posts on this website</p>
	<% end %>
</div>

app/views/posts/index.html.erb
<title>My Projects</title>

<h1>My Projects</h1>

<div class="transbox">
  <%= render "posts" %>
  <%= render "new_admin_post" %>
</div>

app/views/posts/new.html.erb
<title>New Post</title>

<div class="transbox">
	<% if current_admin %>
		<h1>Write your new post</h1>
		<%= render "form" %>
	<% else %>
		<p>You are not authorized to post on this website</p>
	<% end %>
</div>

app/views/posts/show.html.erb
<title><%= @post.title %></title>

<h2><%= @post.title %></h2>

<div class="transbox">
    <p><%= simple_format @post.body %></p>
    <%= render "comments" %>
    <%= render "post_comment" %>
    <%= render "admin_options" %>
</div>